name: Commit validation

on:
  [pull_request]

jobs:
  commitsar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Commitsar Action
        uses: outillage/commitsar@v0.13.0